name: lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  groovy-lint:
    name: Groovy Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
          cache: npm
      - run: npx npm-groovy-lint Jenkinsfile
  renovate-config-validator:
    name: Renovate Config Validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
          cache: npm
      - run: npx --package renovate renovate-config-validator config.js base.json
